language: node_js
node_js:
  - 12
install:
  - yarn install
before_script:
  - mkdir coverage
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./coverage/cc-test-reporter
  - chmod +x ./coverage/cc-test-reporter
  - ./coverage/cc-test-reporter before-build
script:
  - yarn lint
  - yarn run test
after_script:
  - ./coverage/cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
